### ISSUE TITLE
TypeError: unexpected keyword argument 'ssl'

### ISSUE THREAD

**Issue by mecworks** [tve/mqboard#32]
When running the hello world example here: https://github.com/tve/mqboard/blob/master/mqtt_async/hello-world.py and after converting the dictionary access to use dict['key'] method, I get the following error

**Error:**
```
>>> %Run -c $EDITOR_CONTENT
DEBUG:mqtt_async:DNS 192.168.1.158->('192.168.x.xxx', 1883)
INFO:mqtt_async:Connecting to ('192.168.x.xxx', 1883) id=Pico clean=1
DEBUG:mqtt_async:user=asdf passwd-len=10 ssl=None
Traceback (most recent call last):
  File "<stdin>", line 39, in <module>
  File "uasyncio/core.py", line 1, in run_until_complete
  File "uasyncio/core.py", line 1, in run_until_complete
  File "uasyncio/core.py", line 1, in run_until_complete
  File "<stdin>", line 26, in main
  File "/lib/mqtt_async.py", line 609, in connect
  File "/lib/mqtt_async.py", line 189, in connect
  File "/lib/mqtt_async.py", line 28, in open_connection
TypeError: unexpected keyword argument 'ssl'
```

**Micropython version:**
MicroPython v1.19.1-824-g30db33d1e on 2023-01-19; Raspberry Pi Pico W with RP2040

**Platform:**
Raspberry Pi Pico W

**Comment by mecworks** [comment]
I then edited line 28 of mqtt_async.py and removed the `ssl=ssl` parameter.  This got me a little further but ended with another error:

```
>>> %Run -c $EDITOR_CONTENT
DEBUG:mqtt_async:DNS 192.168.x.xxx->('192.168.x.xxx', 1883)
INFO:mqtt_async:Connecting to ('192.168.x.xxx', 1883) id=Pico clean=1
DEBUG:mqtt_async:user=asdf passwd-len=10 ssl=None
Traceback (most recent call last):
  File "<stdin>", line 39, in <module>
  File "uasyncio/core.py", line 1, in run_until_complete
  File "uasyncio/core.py", line 1, in run_until_complete
  File "uasyncio/core.py", line 1, in run_until_complete
  File "<stdin>", line 26, in main
  File "/lib/mqtt_async.py", line 611, in connect
  File "/lib/mqtt_async.py", line 248, in connect
OSError: (-1, 'CONNECT refused: client_id rejected')
```
